# Generated by Django 4.2.1 on 2023-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_employee_alter_user_is_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=60)),
                ('Longitude', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
