# Generated by Django 4.2.1 on 2023-05-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contactenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('image', models.ImageField(upload_to='enquiry_images')),
            ],
        ),
        migrations.DeleteModel(
            name='contactEnquiry',
        ),
    ]
