# Generated by Django 4.2.1 on 2023-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_enquiry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='boxCondition',
            field=models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ecSocket',
            field=models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='loopResistance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
